#!/bin/sh
. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf 0/
cp -r 0.org/ 0.01


runApplication blockMesh
runApplication decomposePar
application=`getApplication`
#runApplication $application
runParallel $application

paraFoam -touch
